package com.woniu.pojo;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseID
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseType
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    private String coursetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseScore
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    private Integer coursescore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseID
     *
     * @return the value of course.courseID
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseID
     *
     * @param courseid the value for course.courseID
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseType
     *
     * @return the value of course.courseType
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public String getCoursetype() {
        return coursetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseType
     *
     * @param coursetype the value for course.courseType
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public void setCoursetype(String coursetype) {
        this.coursetype = coursetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseScore
     *
     * @return the value of course.courseScore
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public Integer getCoursescore() {
        return coursescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseScore
     *
     * @param coursescore the value for course.courseScore
     *
     * @mbggenerated Wed Mar 11 17:03:48 CST 2020
     */
    public void setCoursescore(Integer coursescore) {
        this.coursescore = coursescore;
    }
}